//app.js - generated by MarkLogic Appbuilder 2.0 2014-03-09T13:56:22.110606-06:00

ML.controller.init(controller_config);

var search = ML.createSearch("search");
  
var sidebar = ML.createSidebar("sidebar", sidebar_config);
  


var results = ML.createResults("results", results_config);          
  


ML.controller.loadData();

